In [1]:
import pandas as pd

df = pd.read_csv('C:/potenup3/deeplearning/wheel-safe/output/23,24 output.csv')

df.head()

,folder,prefix,path,slope_avg
0,Depth_023,ZED4_KSC_040620,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,1.51
1,Depth_023,ZED4_KSC_040622,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,1.89
2,Depth_023,ZED4_KSC_040623,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,1.12
3,Depth_023,ZED4_KSC_040624,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,1.18
4,Depth_023,ZED4_KSC_040625,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,2.42

In [2]:
df['slope_avg'] = abs(df['slope_avg'])
df.head()

,folder,prefix,path,slope_avg
0,Depth_023,ZED4_KSC_040620,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,1.51
1,Depth_023,ZED4_KSC_040622,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,1.89
2,Depth_023,ZED4_KSC_040623,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,1.12
3,Depth_023,ZED4_KSC_040624,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,1.18
4,Depth_023,ZED4_KSC_040625,c:\potenup3\deeplearning\wheel-safe\data\raw\D...,2.42

In [ ]:
df = df[df['slope_avg'] < 20]

In [ ]:
before = len(df)
df = df[df['slope_avg'] < 20]
after = len(df)

print('제거 전:', before)
print('제거 후:', after)
print('제거된 개수:', before - after)

제거 전: 1188
제거 후: 1188
제거된 개수: 0

In [ ]:
# 50,51,52,53,54,56,75,201,202,203,204,205,208,210,211,212,214,216,218,219,220,221,222,223,224,226

In [ ]:
drop_idx = [
    48,
    49,
    50,
    51,
    52,
    54,
    73,
    199,
    200,
    201,
    202,
    203,
    206,
    208,
    209,
    210,
    212,
    214,
    216,
    217,
    218,
    219,
    220,
    221,
    222,
    224,
]

df = df.drop(index=drop_idx)
df = df.reset_index(drop=True)

In [4]:
df.to_csv('../output/23&24_output.csv', index=False)